server:
  port: 8762

spring:
  application:
    name: eureka-client-user

# 添加服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # eureka.client.healthcheck.enabled=true只能在application.yml中设置。
    healthcheck:
      enabled: true # 默认启动状态
  # 实例行为有 eureka.instance.*进行配置


